cdef extern from "echomesh/color/FColorList.h" namespace "echomesh::color":
  cdef cppclass FColorList:
    FColor& at(int pos)
    void copy(FColorList that)
    int count(FColor c)
    void extend(FColorList that)
    void eraseOne(int pos)
    void eraseRange(int b, int e)
    int index(FColor c)
    void insertRange(int b1, FColorList cl, int b2, int e2)
    void push_back(FColor c)
    void resize(size_t size)
    void reserve(size_t size)
    void reverse()
    void set(FColor color, int pos)
    int size()
    void sort()
