cdef extern from "echomesh/color/FColorList.h" namespace "echomesh::color":
  cdef cppclass FColorList:
    FColor& at(int pos)
    void combine(FColorList)
    void copy(FColorList)
    int count(FColor)
    void extend(FColorList)
    void eraseOne(int pos)
    void eraseRange(int b, int e)
    void gamma(float)
    int index(FColor)
    void insertRange(int b1, FColorList, int b2, int e2)
    void push_back(FColor)
    void resize(size_t size)
    void reserve(size_t size)
    void reverse()
    void scale(float)
    void set(FColor, int pos)
    void setAll(FColor)
    int size()
    void sort()
